# The URL the site will be built for
base_url = "https://cmbadjusting.com"
title = "AdiDoks"
description = "AdiDoks is a Zola theme helping you build modern documentation websites, which is a port of the Hugo theme Doks for Zola."

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feed = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "authors"}, # Basic definition: no feed or pagination
]

# Whether to build a search index to be used later on by a JavaScript library
# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

[languages.fi]
title="CMB Adjusting"


[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[markdown]
# Whether to do syntax highlighting.
# Theme can be customised by setting the `highlight_theme`
# variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Clinton Bowen Sr."
email = "clinton@cmbadjusting.com"


# If running on netlify.app site, set to true
is_netlify = false

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = "Modern Documentation Theme"


# Set date format in blog publish metadata
timeformat = "%Y-%m-%d %H:%M:%S" # e.g. 2021-05-01 09:19:42
timezone = "UTC"

# Edit page on reposity or not
edit_page = false
docs_repo = "https://github.com/cmbadjusting/adidoks"
repo_branch = "main"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = false
library = "katex"  # options: "katex", "mathjax". default is "katex".

## Open Graph + Twitter Cards
[extra.open]
enable = false
# this image will be used as fallback if a page has no image of its own
image = "doks.png"
og_locale = "en_US"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo-doks.png"
section = "about" # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = false

# Footer contents
[extra.footer]
info = 'Powered by <a href="https://www.netlify.com/">Netlify</a>, <a href="https://www.getzola.org/">Zola</a>, and <a href="https://github.com/aaranxu/adidoks">AdiDoks</a>'

[[extra.footer.nav]]
name = "Privacy"
url = "/privacy-policy/"
weight = 10

[[extra.footer.nav]]
name = "Code of Conduct"
url = "/docs/contributing/code-of-conduct/"
weight = 20

# The homepage contents
[extra]
lead = ''
url = "/"
url_button = "aaa"
repo_version = "GitHub v0.1.0"
repo_license = "Open-source MIT License."
repo_url = "https://github.com/cmbadjusting/adidoks"

# Menu items
[[extra.menu.main]]
name = "About"
section = "about"
url = "/about"
weight = 10

[[extra.menu.main]]
name = "Frequently Asked Questions"
section = "faqs"
url = "/faqs"
weight = 20

[[extra.menu.main]]
name = "Services"
section = "services"
url = "/services"
weight = 30

[[extra.menu.main]]
name = "Contact"
section = "/contact"
url = "contact"
weight = 40

[[extra.menu.main]]
name = "Client References"
section = "references"
url = "/references"
weight = 50

[[extra.menu.main]]
name = "Case Study"
section = "case status"
url = "/case-study"
weight = 60